name: build

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [ '1.21' ]
    name: Build
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/v/}

      - name: Build
        run: |
          bash build.sh -v "v${{ steps.get_version.outputs.VERSION }}" -P -p "windows/amd64,linux/amd64,linux/arm64,darwin/amd64,darwin/arm64"

      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
            repo_token: "${{ secrets.GITHUB_TOKEN }}"
            automatic_release_tag: "v${{ steps.get_version.outputs.VERSION }}"
            title: "Version ${{ steps.get_version.outputs.VERSION }}"
            prerelease: false
            files: |
                build/*
